package com.telemed.backend.service;
import com.lowagie.text.*;
import com.lowagie.text.Font;
import com.lowagie.text.pdf.*;

import java.awt.*;

public class FooterPageEvent extends PdfPageEventHelper {

    private final Font footerFont =
            FontFactory.getFont(FontFactory.HELVETICA, 8, Color.GRAY);

    @Override
    public void onEndPage(PdfWriter writer, Document document) {

        Phrase footer = new Phrase(
                "Generated by TeleMed Humla Digital Health System",
                footerFont
        );

        ColumnText.showTextAligned(
                writer.getDirectContent(),
                Element.ALIGN_CENTER,
                footer,
                (document.right() + document.left()) / 2,
                document.bottom() - 10,
                0
        );
    }
}