package com.telemed.backend.service;

import com.lowagie.text.*;
import com.lowagie.text.pdf.PdfPCell;
import com.lowagie.text.pdf.PdfPTable;
import com.lowagie.text.pdf.PdfWriter;
import com.lowagie.text.pdf.draw.LineSeparator;
import com.telemed.backend.entity.MedicalRecord;
import com.telemed.backend.entity.Patient;
import org.springframework.stereotype.Service;

import java.awt.Color;
import java.io.ByteArrayOutputStream;
import java.util.Map;

@Service
public class MedicalRecordPdfService {

    public byte[] generateSingleMedicalRecordPdf(Patient patient, MedicalRecord record) {
        try {
            Document document = new Document(PageSize.A4);
            ByteArrayOutputStream out = new ByteArrayOutputStream();
            PdfWriter.getInstance(document, out);
            document.open();

            Font titleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 18, Color.BLACK);
            Font subTitleFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 12, Color.DARK_GRAY);
            Font labelFont = FontFactory.getFont(FontFactory.HELVETICA_BOLD, 10, Color.BLACK);
            Font textFont = FontFactory.getFont(FontFactory.HELVETICA, 10, Color.BLACK);

            Paragraph header = new Paragraph("TELEMED HUMLA - MEDICAL RECORD", titleFont);
            header.setAlignment(Element.ALIGN_CENTER);
            document.add(header);

            document.add(new Paragraph(" "));
            document.add(new LineSeparator());
            document.add(new Paragraph(" "));

            PdfPTable infoTable = new PdfPTable(2);
            infoTable.setWidthPercentage(100);
            infoTable.setSpacingAfter(10f);

            addTableCell(infoTable, "Patient Name:", patient.getFirstName() + " " + patient.getLastName(), labelFont, textFont);
            addTableCell(infoTable, "Age:", String.valueOf(patient.getAge()), labelFont, textFont);
            addTableCell(infoTable, "Date of Birth:", patient.getDateOfBirth().toString(), labelFont, textFont);
            addTableCell(infoTable, "Attending Provider:", record.getCreator(), labelFont, textFont);

            document.add(infoTable);
            document.add(new LineSeparator());
            document.add(new Paragraph(" "));

            document.add(new Paragraph("CLINICAL EVALUATION", subTitleFont));
            document.add(new Paragraph(" "));

            for (Map.Entry<String, String> entry : record.getPatientHistory().entrySet()) {
                Paragraph keyPara = new Paragraph(entry.getKey().toUpperCase(), labelFont);
                keyPara.setSpacingBefore(10f);
                document.add(keyPara);

                Paragraph valuePara = new Paragraph(entry.getValue(), textFont);
                valuePara.setIndentationLeft(20f);
                document.add(valuePara);
            }

            Paragraph footer = new Paragraph("\n\nGenerated by TeleMed Humla Digital Health System",
                    FontFactory.getFont(FontFactory.HELVETICA, 8, Color.GRAY));
            footer.setAlignment(Element.ALIGN_CENTER);
            document.add(footer);

            document.close();
            return out.toByteArray();

        } catch (Exception e) {
            throw new RuntimeException("Error generating PDF", e);
        }
    }

    private void addTableCell(PdfPTable table, String label, String value, Font labelFont, Font textFont) {
        PdfPCell labelCell = new PdfPCell(new Phrase(label, labelFont));
        labelCell.setBorder(Rectangle.NO_BORDER);
        table.addCell(labelCell);

        PdfPCell valueCell = new PdfPCell(new Phrase(value, textFont));
        valueCell.setBorder(Rectangle.NO_BORDER);
        table.addCell(valueCell);
    }
}